development:
  adapter: postgresql
  pool: 5
  # these are our new parameters
  encoding: UTF-8
  database: projeto
  host: localhost
  username: nascimento
  password: silva

test:
  # this won't work
  adapter: postgresql
  encoding: unicode
  database: projeto 
  pool: 5
  username: nascimento
  password: silva

production:
  # this won't work
  adapter: postgresql
  encoding: unicode
  database: projeto
  pool: 5
  username: nascimento
  password: silva
